POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "SWPPX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-19T145300.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "SWPPX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-19T145247.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "SWPPX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T210451.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 159
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "SWPPX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

//{
//  "ticker": "TSLA",
//  "initialInvestment": 10000,
//  "timeInYears": 10
//}

<> 2025-01-18T205803.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 159
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "FXAIX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

//{
//  "ticker": "TSLA",
//  "initialInvestment": 10000,
//  "timeInYears": 10
//}

<> 2025-01-18T205706.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 159
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "FXAIX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

//{
//  "ticker": "TSLA",
//  "initialInvestment": 10000,
//  "timeInYears": 10
//}

<> 2025-01-18T205505.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 159
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

//{
//  "ticker": "TSLA",
//  "initialInvestment": 10000,
//  "timeInYears": 10
//}

<> 2025-01-18T205417.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T205055.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204911.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204805.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204651.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204511.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204406.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204321.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204154.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204105.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T204034.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T203841.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T202533.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T202229.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T202136.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "TSLA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T201731.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "FXAIX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T201629.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "NVDA",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T201539.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "GOOG",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T201412.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T201120.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T201020.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T200731.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T200544.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value?ticker=VFIAX&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 0

<> 2025-01-18T183155.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 74
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 10
}

<> 2025-01-18T175817.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 5
}

<> 2025-01-18T175758.200.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 5
}

<> 2025-01-18T175633.405.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 5
}

<> 2025-01-18T175557.405.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 5
}

<> 2025-01-18T175554.405.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 5
}

<> 2025-01-18T175552.405.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 5
}

<> 2025-01-18T175547.405.json

###

POST http://localhost:8080/api/mutualfunds/future-value
Content-Type: application/json
Content-Length: 73
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "ticker": "VFIAX",
  "initialInvestment": 10000,
  "timeInYears": 5
}

<> 2025-01-18T175029.405.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=GOOG&initialInvestment=10000&timeInYears=15
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T180727.200.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=GOOG&initialInvestment=10000&timeInYears=15
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T180427.200.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=FXAIX&initialInvestment=10000&timeInYears=15
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T180250.200.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T180134.200.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T180052.500.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T175923.500.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T175709.500.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T175414.500.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T175240.500.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T174742.500.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T174649.500.json

###

GET http://localhost:8080/api/mutualfunds/future-value?ticker=NVDA&initialInvestment=10000&timeInYears=5
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-01-16T174549.500.json

###

